"""Tasks, seats and finalization. Pure state; the orchestrator does the side effects."""

from __future__ import annotations

from panopticon.model import Task


class TaskBoard:
    ARCHIVE_SHOWN = 20

    def __init__(self) -> None:
        self.tasks: dict[str, Task] = {}

    # queries
    def open_tasks(self) -> list[Task]: ...
    def archive(self) -> list[Task]: ...
    def get(self, task_id: str) -> Task | None: ...
    def task_of(self, agent: str) -> Task | None: ...
    def render(self) -> str:
        """The view returned by the view_task_board tool."""
        ...

    # mutations
    def create(self, creator: str, title: str, description: str, roles: list[str]) -> Task: ...
    def assign(self, agent: str, task_id: str, role: str) -> tuple[Task, bool]:
        """Returns (task, task_just_became_ready). Raises ValueError on a bad seat."""
        ...

    def unassign(self, agent: str, task_id: str) -> Task: ...
    def finalize(self, agent: str, task_id: str, reason: str, conclusion: str) -> tuple[Task, bool]:
        """Returns (task, all_seats_agreed)."""
        ...

    def cancel_finalize(self, agent: str, task_id: str) -> Task: ...
    def start(self, task: Task, worktree: str) -> None: ...
    def archive_task(self, task: Task, outcome: str) -> None: ...
